name: タスク管理
description: タスク管理Issue作成テンプレート
title: "task title"
labels: []
assignees: []
body:
  - type: input
    id: request_summary
    attributes:
      label: タスク内容
      placeholder: タスクの内容を簡潔に
    validations:
      required: true

  - type: textarea
    id: request_detail
    attributes:
      label: タスク詳細
      placeholder: タスクの詳細な内容を記載してください
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      options:
        - 🔴 高
        - 🟡 中
        - 🟢 低
    validations:
      required: true

  - type: input
    id: due_date
    attributes:
      label: 完了予定日
      placeholder: "例: 2026-04-30"
    validations:
      required: false
