name: ✏ タスク作成
description: タスクを作成する
title: "task title"
labels: []
assignees: []
body:
  - type: input
    id: task_summary
    attributes:
      label: タスク概要
      placeholder: タスクの内容を簡潔に記載してください。
    validations:
      required: true

  - type: textarea
    id: task_detail
    attributes:
      label: タスク詳細
      value: |
        # Asis


        # Tobe
        
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      options:
        - 保留
        - ☆
        - ☆☆
        - ☆☆☆
        - ☆☆☆☆
        - ☆☆☆☆☆
    validations:
      required: false

  - type: input
    id: due_date
    attributes:
      label: 完了予定日
      placeholder: "例: 2026-04-30"
    validations:
      required: false
